"""add upload history table

Revision ID: a946082cf036
Revises: 18667fab5644
Create Date: 2025-07-17 13:36:34.204193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a946082cf036'
down_revision: Union[str, None] = '18667fab5644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Nombre del archivo subido'),
    sa.Column('upload_date', sa.DateTime(), nullable=False, comment='Fecha y hora de subida'),
    sa.Column('user_dni', sa.String(length=20), nullable=False, comment='DNI/NIE del usuario que subió'),
    sa.Column('user_name', sa.String(length=200), nullable=False, comment='Nombre completo del usuario'),
    sa.Column('document_type', sa.String(length=20), nullable=False, comment='Tipo de documento: nominas/dietas'),
    sa.Column('month', sa.String(length=2), nullable=False, comment='Mes del documento'),
    sa.Column('year', sa.String(length=4), nullable=False, comment='Año del documento'),
    sa.Column('total_pages', sa.Integer(), nullable=False, comment='Total de páginas procesadas'),
    sa.Column('successful_pages', sa.Integer(), nullable=False, comment='Páginas procesadas exitosamente'),
    sa.Column('failed_pages', sa.Integer(), nullable=False, comment='Páginas que fallaron'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado: processing/completed/error'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualización'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_history_id'), 'upload_history', ['id'], unique=False)
    op.create_index(op.f('ix_upload_history_user_dni'), 'upload_history', ['user_dni'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_history_user_dni'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_id'), table_name='upload_history')
    op.drop_table('upload_history')
    # ### end Alembic commands ###
