"""crear_tabla_usuarios_inicial

Revision ID: 18667fab5644
Revises: 
Create Date: 2025-07-15 09:10:43.078733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18667fab5644'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni_nie', sa.String(length=20), nullable=False, comment='DNI o NIE del usuario'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Nombre'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Apellidos'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email corporativo'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Teléfono'),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', name='userrole'), nullable=False, comment='Rol en el sistema'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='Departamento'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='Puesto de trabajo'),
    sa.Column('hire_date', sa.DateTime(), nullable=True, comment='Fecha de contratación'),
    sa.Column('birth_date', sa.DateTime(), nullable=True, comment='Fecha de nacimiento'),
    sa.Column('address', sa.Text(), nullable=True, comment='Dirección completa'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='Ciudad'),
    sa.Column('postal_code', sa.String(length=10), nullable=True, comment='Código postal'),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True, comment='Nombre contacto emergencia'),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True, comment='Teléfono contacto emergencia'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Password hasheado'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Usuario activo'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verificado'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='Ruta al avatar del usuario'),
    sa.Column('user_folder_path', sa.String(length=500), nullable=True, comment='Ruta a la carpeta personal del usuario'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de última actualización'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Último inicio de sesión'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dni_nie'), 'users', ['dni_nie'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dni_nie'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
